"""
Groq SQL Agent - converts natural language questions into SAFE SQLite SELECT queries.
"""
import json
import re
from typing import Dict

from ai_agents.groq_service import get_groq_service


class SQLAgent:
    def __init__(self):
        self.schema = """
SQLite database schema:
customers(id, name, email, phone, city, country, segment, created_at)
products(id, name, price, category, stock, description, created_at)
sales(id, customer_id, product_id, amount, quantity, sale_date, status, payment_method)
Relationships:
sales.customer_id = customers.id
sales.product_id = products.id
"""

    def generate_sql(self, question: str) -> Dict[str, str]:
        prompt = f"""
You are a SQLite expert for a business analytics dashboard.
Generate exactly one safe read-only SQL SELECT query for the user question.

{self.schema}

Rules:
- Use SQLite syntax only.
- Only SELECT queries are allowed.
- Do not use INSERT, UPDATE, DELETE, DROP, ALTER, CREATE, TRUNCATE, PRAGMA, ATTACH.
- Prefer joins when customer/product names are needed.
- For dates use strftime(), not DATE_TRUNC().
- Return JSON only with keys: sql, explanation.

User question: {question}
"""
        try:
            content = get_groq_service().chat(
                [
                    {"role": "system", "content": "Return valid JSON only. No markdown."},
                    {"role": "user", "content": prompt},
                ],
                temperature=0.1,
                max_tokens=350,
            )
            data = json.loads(self._extract_json(content))
            sql = data.get("sql", "").strip().rstrip(";")
            ok, message = self.validate_sql(sql)
            if not ok:
                raise ValueError(message)
            return {
                "sql": sql,
                "explanation": data.get("explanation", "Generated by Groq SQL Agent"),
            }
        except Exception:
            return self._fallback_sql(question)

    def validate_sql(self, sql: str):
        if not sql:
            return False, "Empty SQL generated"

        normalized = re.sub(r"\s+", " ", sql.strip()).upper()
        blocked = [
            "INSERT", "UPDATE", "DELETE", "DROP", "ALTER", "CREATE",
            "TRUNCATE", "PRAGMA", "ATTACH", "DETACH", "REPLACE"
        ]
        if not normalized.startswith("SELECT"):
            return False, "Only SELECT queries are allowed"
        for word in blocked:
            if re.search(rf"\b{word}\b", normalized):
                return False, f"Blocked unsafe SQL keyword: {word}"
        if ";" in sql:
            return False, "Multiple SQL statements are not allowed"
        return True, "SQL is safe"

    def _extract_json(self, content: str) -> str:
        match = re.search(r"\{.*\}", content, re.DOTALL)
        return match.group(0) if match else content

    def _fallback_sql(self, question: str) -> Dict[str, str]:
        q = question.lower()
        if "customer" in q or "client" in q:
            sql = """
SELECT c.name, c.city, c.segment, COUNT(s.id) AS orders, SUM(s.amount) AS revenue
FROM customers c
LEFT JOIN sales s ON c.id = s.customer_id
GROUP BY c.id, c.name, c.city, c.segment
ORDER BY revenue DESC
LIMIT 10
""".strip()
        elif "product" in q or "item" in q:
            sql = """
SELECT p.name, p.category, COUNT(s.id) AS sales_count, SUM(s.amount) AS revenue
FROM products p
LEFT JOIN sales s ON p.id = s.product_id
GROUP BY p.id, p.name, p.category
ORDER BY revenue DESC
LIMIT 10
""".strip()
        elif "month" in q or "trend" in q:
            sql = """
SELECT strftime('%Y-%m', sale_date) AS month, SUM(amount) AS revenue, COUNT(*) AS sales_count
FROM sales
GROUP BY strftime('%Y-%m', sale_date)
ORDER BY month
""".strip()
        else:
            sql = "SELECT COUNT(*) AS sales_count, SUM(amount) AS total_revenue, AVG(amount) AS average_sale FROM sales"
        return {"sql": sql, "explanation": "Fallback SQL used because AI SQL generation failed."}
